### ISSUE TITLE
Cannot get device instance for empty CD drive on Windows

### ISSUE THREAD

**Issue by RibShark** [TkTech/smartie#20]
When attempting to run get_device on Windows with an empty CD drive, the CreateFileA call returns a "device not ready" error:
```
Traceback (most recent call last):
  File "X:\PycharmProjects\DriveExperiments\main.py", line 6, in <module>
    with get_device('E:') as device:
         ^^^^^^^^^^^^^^^^
  File "X:\PycharmProjects\DriveExperiments\.venv\Lib\site-packages\smartie\scsi\windows.py", line 33, in __enter__
    raise ctypes.WinError(ctypes.get_last_error())
PermissionError: [WinError 21] The device is not ready.
```

A drive shouldn't need to have media inserted in order to send/receive SCSI commands.

**Comment by TkTech** [comment]
Huh, that's surprising. This is failing on the initial device open, which means we're going to need to handle CD drives differently on Windows.

I don't have any physical hardware with a CD drive anymore, if anyone wants to take a crack at it.

**Comment by TkTech** [comment]
@RibShark Is this CD drive connected via USB?

**Comment by RibShark** [comment]
> @RibShark Is this CD drive connected via USB?

Yes, it is.

**Comment by jackeichen** [comment]
@RibShark  refer to https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#win32-device-namespaces

I prefer to use a Win32 device namespace instead of the Win32 file namespace, and smartie could detect and return it with function [get_all_device](https://github.com/TkTech/smartie/blob/main/smartie/device.py#L116).

In my test, the CdRom device could be opened, but the ATA or SCSi commands should be incompatible with CdRom device type.

```
>>> with get_device("\\\\.\\CdRom1") as d:
...     d.inquiry()
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "D:\software\python3.12.3\Lib\site-packages\smartie\scsi\__init__.py", line 126, in inquiry
    response = self.issue_command(Direction.FROM, inquiry_command, inquiry)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\python3.12.3\Lib\site-packages\smartie\scsi\windows.py", line 92, in issue_command
    self.parse_sense(bytearray(header_with_buffer.sense))
  File "D:\software\python3.12.3\Lib\site-packages\smartie\scsi\__init__.py", line 87, in parse_sense
    raise SenseError(sense.sense_key, sense=sense)
smartie.scsi.errors.SenseError: <SenseError(error_code=0x05, err='Illegal Request')>
>>>
```

**Comment by jackeichen** [comment]
@TkTech  Maybe something different between your device and me. 
Here is my deivce:
http://iodd.kr/wordpress/product/iodd-2541/
